// Auto-generated by Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '13.0.5'
  }
  public: {
    Tables: {
      bids: {
        Row: {
          created_at: string | null
          id: string
          is_deleted: boolean | null
          item_id: string
          user_id: string
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_deleted?: boolean | null
          item_id: string
          user_id: string
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          is_deleted?: boolean | null
          item_id?: string
          user_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: 'bids_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'finishes'
            referencedColumns: ['item_id']
          },
          {
            foreignKeyName: 'bids_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bids_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      items: {
        Row: {
          auction_end: string | null
          auction_start: string | null
          bid_step: number
          created_at: string | null
          description: string
          id: string
          is_donation: boolean | null
          payment_status: Database['public']['Enums']['payment_status'] | null
          photos: string[]
          proof_url: string | null
          starting_bid: number | null
          status: Database['public']['Enums']['item_status'] | null
          title: string
        }
        Insert: {
          auction_end?: string | null
          auction_start?: string | null
          bid_step: number
          created_at?: string | null
          description: string
          id?: string
          is_donation?: boolean | null
          payment_status?: Database['public']['Enums']['payment_status'] | null
          photos: string[]
          proof_url?: string | null
          starting_bid?: number | null
          status?: Database['public']['Enums']['item_status'] | null
          title: string
        }
        Update: {
          auction_end?: string | null
          auction_start?: string | null
          bid_step?: number
          created_at?: string | null
          description?: string
          id?: string
          is_donation?: boolean | null
          payment_status?: Database['public']['Enums']['payment_status'] | null
          photos?: string[]
          proof_url?: string | null
          starting_bid?: number | null
          status?: Database['public']['Enums']['item_status'] | null
          title?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          course: string | null
          created_at: string | null
          email: string
          id: string
          is_insper: boolean | null
          name: string
          photo: string | null
          semester: string | null
          whatsapp: string
        }
        Insert: {
          course?: string | null
          created_at?: string | null
          email: string
          id: string
          is_insper?: boolean | null
          name: string
          photo?: string | null
          semester?: string | null
          whatsapp: string
        }
        Update: {
          course?: string | null
          created_at?: string | null
          email?: string
          id?: string
          is_insper?: boolean | null
          name?: string
          photo?: string | null
          semester?: string | null
          whatsapp?: string
        }
        Relationships: []
      }
    }
    Views: {
      finishes: {
        Row: {
          final_value: number | null
          finished_at: string | null
          item_id: string | null
          item_title: string | null
          payment_status: Database['public']['Enums']['payment_status'] | null
          proof_url: string | null
          user_id: string | null
          winner_email: string | null
          winner_name: string | null
          winner_whatsapp: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'bids_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Functions: {
      can_view_finish: { Args: { finish_user_id: string }; Returns: boolean }
    }
    Enums: {
      item_status: 'draft' | 'scheduled' | 'active' | 'finished'
      payment_status: 'pending' | 'paid' | 'delivered'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      item_status: ['draft', 'scheduled', 'active', 'finished'],
      payment_status: ['pending', 'paid', 'delivered'],
    },
  },
} as const
